# Generated by Django 2.0.2 on 2020-08-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorias',
            field=models.ManyToManyField(related_name='get_posts', to='products.Category', verbose_name='Categorias'),
        ),
    ]
